### PR TITLE
Bump DbVisualizer package to v10.0.10

### PR DESCRIPTION
**Pull request by ziggythehamster**
This updates DbVisualizer to v10.0.10 and uses the latest Chocolatey pattern for chocolateyInstall.ps1.

### CODE REVIEW

**Comment by jjathman** [comment]
Thanks!

**Comment by jjathman** [comment]
@ziggythehamster - would you like to take over maintenance of this? I actually don't use Chocolatey anymore so I'm probably not a good person to be responsible for it.

**Comment by ziggythehamster** [comment]
This was my first Chocolatey package, but I'd be happy to take over. What's the process for that?

**Comment by jjathman** [comment]
@ziggythehamster honestly not really sure. Let me see if I can add an additional maintainer to the chocolatey package.

**Comment by jjathman** [comment]
@ziggythehamster is this your chocolatey account name as well?

**Comment by ziggythehamster** [comment]
Yes, and I've just confirmed maintainership as well

**Pull request merged**
